name: Go unit and integration tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Integration tests
      run: DOCKER_BUILDKIT=0 docker compose -f docker-compose.yaml -f docker-compose.test.yaml up --force-recreate --no-deps --exit-code-from test

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Unit tests
      run: go test ./... -v
